name: CD to Staging/Development

on:
  workflow_run:
    workflows: ["Ruby on Rails CI"]
    types:
      - completed  # Trigger only when the tests workflow completes and passes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    env:
        ARM_CLIENT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}
        ARM_TENANT_ID: ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
    
    # Pull code from Giuthub Repo
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    # Login to Azure
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
       terraform_version: '1.7.0'  # Specify the version you need

    # Initialise Terraform
    - name: Terraform Init
      working-directory: ./Terraform
      run: terraform init

    # Run Terraform Plan
    - name: Terraform Plan
      working-directory: ./Terraform
      run: terraform plan -out=tfplan

    # Terraform Apply - Auto approve
    - name: Terraform Apply
      working-directory: ./Terraform
      run: terraform apply -auto-approve tfplan

    # Set up Docker Build
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 
    
    # Build and push Docker image to acr
    - name: Build and push Docker image to registry
      run: |
        docker build --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} \
         -t ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.TERRAFORM_CONTAINER_NAME }}:latest .
        echo ${{ secrets.TERRAFORM_ACR_REGISTRY_PASSWORD }} | docker login ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io -u ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }} --password-stdin
        docker push ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.TERRAFORM_CONTAINER_NAME }}:latest
      
    # Deploy to Staging site
    - name: Deploy to Staging 
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.TERRAFORM_AZURE_APP_NAME }}
        images: ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.TERRAFORM_CONTAINER_NAME }}:latest

    # Deploy to Development site