name: CD to Staging/Development

on:
  workflow_run:
    workflows: ["Ruby on Rails CI"]
    types:
      - completed  # Trigger only when the tests workflow completes and passes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2 

    - name: Build and push Docker image to registry
      run: |
        docker build --build-arg RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }} \
         -t ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.TERRAFORM_CONTAINER_NAME }}:latest .
        echo ${{ secrets.TERRAFORM_ACR_REGISTRY_PASSWORD }} | docker login ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io -u ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }} --password-stdin
        docker push ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.TERRAFORM_CONTAINER_NAME }}:latest
      
    # Deploy to Staging
    - name: Deploy to Staging 
      uses: azure/webapps-deploy@v2
      with:
        app-name: terraform-ruby-web-app
        images: ${{ secrets.TERRAFORM_ACR_REGISTRY_USERNAME }}.azurecr.io/${{ secrets.TERRAFORM_CONTAINER_NAME }}:latest